import swaggerAutogen from 'swagger-autogen';
import logger from './logger.js';

const outputFile = './swagger_output.json';
const endpointsFiles = ['./routes/message.js'];

const doc = {
  info: {
    version: '1.0.0',
    title: 'Message',
    description: 'Documentation automatically generated by the <b>swagger-autogen</b> module.',
  },
  host: 'localhost:3000',
  basePath: '/',
  schemes: ['http', 'https'],
  consumes: ['application/json'],
  produces: ['application/json'],
  tags: [
    {
      name: 'Message',
      description: 'Endpoints for essage operations',
    },
  ],
  definitions: {
    Message: {
      userId: 1,
      title: 'getAllMessages',
      content: 'bbb',
    },
    AddMessage: {
      $userId: 1,
      $title: 'aaa',
      $content: 'bbb',
    },
  },
};
swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  logger.info('swagger');
});
export default doc;
